spring.application.name=fitness-tracker

# URL adresa pre tvoju novú databázu
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_app

# Prihlasovacie údaje
spring.datasource.username=postgres
spring.datasource.password=lakyneckomiminka@2006

# Hibernate a JPA nastavenia
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true